### PR TITLE
Adds Plymouth Galway Worsted colors, tweaks row counting, typo fix

### PR DESCRIPTION
**Pull request by epersonae**
Teal & Yellow

(I'm trying a pull request with something much more simple!)

### CODE REVIEW

**Comment by epersonae** [comment]
After looking at a variety of knitting patterns I have on hand, looks like row counting doesn't usually include casting on and binding off, so I've renumbered accordingly.

**Comment by brennx0r** [comment]
The row changes look good! It looks like there's only two colors of yarn listed for the Galway - is this intentional?

**Comment by epersonae** [comment]
I've only bought those 2 colors. I'll add the other 2 after I pick them up.

**Comment by brennx0r** [comment]
Looks good! Thank you for doing this.

**Pull request merged**
