### PR TITLE
Mostly minor formatting issues

### PR DESCRIPTION
**Pull request by epersonae**
I added the colors for teal & yellow in Plymouth Galway Worsted.

Also removed CO/BO from row numbering in sections I've completed, added some additional notes.

### CODE REVIEW

**Comment by brennx0r** [comment]
Sorry there - I didn't see that you made this pull request before checking in my changes to master. Could you do a quick merge to resolve the conflicts? Thank you! <3

**Comment by epersonae** [comment]
It's a little bit "ow my brain" -- collaborating on a public Github project is entirely new to me, and I only just figured out how to make a pull request across a fork...

I might not get into it today (doing yardwork this afternoon) but will figure it out tomorrow if not. :)

**Comment by brennx0r** [comment]
Sure! No worries. Please let me know if you have any questions - I'm happy to help. :)

**Comment by epersonae** [comment]
I realized that I kinda want to reset some of my stuff based on your stuff. So I'll submit a fresh pull request when I'm ready. :)

**Comment by brennx0r** [comment]
Cool - thanks for the heads up!

**Pull request closed without merging**
